name: cinema
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6

dev_dependencies:
  build_runner: any
  flutter_gen_runner: any
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/png/


scripts:
  clean: flutter clean && flutter pub get
  i: flutter pub add
  sha: cd android && ./gradlew signingReport && cd ..
  asset: dart run build_runner build
  apk: flutter build apk --target-platform android-arm64 --analyze-size
  run_release: flutter run release