name: cinema
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  dio: ^5.6.0
  get_storage: ^2.1.1
  delightful_toast: ^1.1.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  pretty_dio_logger: ^1.4.0
  logger: ^2.4.0

dev_dependencies:
  build_runner: any
  flutter_gen_runner: any
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/png/


scripts:
  clean: flutter clean && flutter pub get
  get: flutter pub get
  i: flutter pub add
  sha: cd android && ./gradlew signingReport && cd ..
  asset: dart run build_runner build
  apk: flutter build apk --target-platform android-arm64 --analyze-size
  run_release: flutter run release